### ISSUE TITLE
Connection broke since the last release 20227

### ISSUE THREAD

**Issue by Next9999** [spbrogan/sensor.mopeka_pro_check#19]
Connection broke since the last release 20227

https://www.home-assistant.io/blog/2022/07/06/release-20227/#breaking-changes

This error originated from a custom integration.

Logger: homeassistant.core
Source: custom_components/mopeka_pro_check/sensor.py:116
Integration: mopeka_pro_check (documentation)
First occurred: 11:29:12 (1 occurrences)
Last logged: 11:29:12

Error executing service: <ServiceCall mopeka_pro_check.discovered (c:01G7W2V1NKXFHR41JEK6VSCGVK)>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1731, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1756, in _execute_service
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/mopeka_pro_check/sensor.py", line 116, in ReportMopekaDevicesWithButtonPressed
    service.Start()
  File "/usr/local/lib/python3.10/site-packages/mopeka_pro_check/service.py", line 151, in Start
    self._start()
  File "/usr/local/lib/python3.10/site-packages/mopeka_pro_check/service.py", line 165, in _start
    self._adapter = get_provider().get_adapter(self._hci_index)
  File "/usr/local/lib/python3.10/site-packages/bleson/providers/linux/linux_provider.py", line 12, in get_adapter
    adapter.on()
  File "/usr/local/lib/python3.10/site-packages/bleson/providers/linux/linux_adapter.py", line 100, in on
    self.send_cmd_value(HCIDEVUP, self.device_id)
  File "/usr/local/lib/python3.10/site-packages/bleson/providers/linux/linux_adapter.py", line 47, in send_cmd_value
    fcntl.ioctl(self._socket.fileno(), cmd, value)
TimeoutError: [Errno 110] Operation timed out

Logger: homeassistant.components.bluetooth_tracker.device_tracker
Source: components/bluetooth_tracker/device_tracker.py:127
Integration: bluetooth_tracker (documentation, issues)
First occurred: 10:57:55 (158 occurrences)
Last logged: 11:29:19

Error looking up Bluetooth device
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/bluetooth/bluez.py", line 289, in _gethcisock
    sock = _bt.hci_open_dev (device_id)
_bluetooth.error: no available bluetoot devices

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/bluetooth_tracker/device_tracker.py", line 167, in perform_bluetooth_update
    friendly_name = await hass.async_add_executor_job(lookup_name, mac)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/bluetooth_tracker/device_tracker.py", line 127, in lookup_name
    return bluetooth.lookup_name(mac, timeout=5)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.10/site-packages/bluetooth/bluez.py", line 61, in lookup_name
    sock = _gethcisock ()
  File "/usr/local/lib/python3.10/site-packages/bluetooth/bluez.py", line 291, in _gethcisock
    raise BluetoothError ("error accessing bluetooth device")
bluetooth.btcommon.BluetoothError: error accessing bluetooth device

This error originated from a custom integration.

Logger: custom_components.hacs
Source: custom_components/hacs/repositories/base.py:1020
Integration: HACS (documentation, issues)
First occurred: 11:24:21 (1 occurrences)
Last logged: 11:24:21

<Integration spbrogan/sensor.mopeka_pro_check> Cannot connect to host api.github.com:443 ssl:default [Try again]

**Comment by spbrogan** [comment]
Yes. I was just reading the breaking changes from the July release of HA. Seems that many of the BLE libraries are no longer supported.  I’ll take a look at porting to a new lib. I don’t expect it to be too difficult. 

It will probably be a change in this repo https://github.com/spbrogan/mopeka_pro_check

if you use esphome on an esp32 you can use that instead of this as personally I have moved over to that as a solution.

**Comment by Next9999** [comment]
i am trying to used ESP32 but i got this error, ant help would be apreaciated

![image](https://user-images.githubusercontent.com/54117519/179356190-2e04c1ea-52a8-4130-8df1-6c8e654591f3.png)

**Comment by Next9999** [comment]
Sensors are back :-)
