### ISSUE TITLE
Installed via HACS and getting an error

### ISSUE THREAD

**Issue by kevinkey619** [spbrogan/sensor.mopeka_pro_check#3]
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/mopeka_pro_check/sensor.py", line 221, in setup_platform
    service.Start()
  File "/srv/homeassistant/lib/python3.9/site-packages/mopeka_pro_check/service.py", line 151, in Start
    self._start()
  File "/srv/homeassistant/lib/python3.9/site-packages/mopeka_pro_check/service.py", line 165, in _start
    self._adapter = get_provider().get_adapter(self._hci_index)
  File "/srv/homeassistant/lib/python3.9/site-packages/bleson/providers/linux/linux_provider.py", line 11, in get_adapter
    adapter.off()
  File "/srv/homeassistant/lib/python3.9/site-packages/bleson/providers/linux/linux_adapter.py", line 103, in off
    self.send_cmd_value(HCIDEVDOWN, self.device_id)
  File "/srv/homeassistant/lib/python3.9/site-packages/bleson/providers/linux/linux_adapter.py", line 47, in send_cmd_value
    fcntl.ioctl(self._socket.fileno(), cmd, value)
PermissionError: [Errno 1] Operation not permitted

**Comment by kevinkey619** [comment]
I figured it out. If you're running Home Assistant core via Docker like I am, you need to perform the below steps to get Bluetooth working properly:

https://www.home-assistant.io/integrations/bluetooth_le_tracker/

sudo apt install bluetooth

sudo apt-get install libcap2-bin
sudo setcap 'cap_net_raw,cap_net_admin+eip' $(readlink -f $(which python3))
sudo setcap 'cap_net_raw+ep' $(readlink -f $(which hcitool))

Restart Home Assistant

**Comment by spbrogan** [comment]
thanks for the update.  I have seen a couple of issues that i think are related to sharing the BLE adapter with other integrations.  I might do some work to see if i can get this included into https://github.com/custom-components/ble_monitor

On a different tangent: Are you able to map the bluetooth adapter into more than one container?
